library:
  source-dirs: src
  dependencies:
  - text
  - persistent-template
  - persistent-sqlite
  - persistent-postgresql
  - yaml
  - persistent
  - base >=4.7 && <5
  - aeson
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - jose-jwt
  - jose
  - wai
  - warp
  - bytestring
  - mtl
  - transformers
  - lens
  - protolude
  - monad-logger
  - resourcet
  exposed-modules:
  - Lib
tests:
  sleepchart-server-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - sleepchart-server
    - protolude
    - bytestring
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - servant
    - servant-server
    - servant-auth
    - servant-auth-server
    - jose-jwt
    - jose
copyright: 2019 Author name here
category: Web
maintainer: example@example.com
name: sleepchart-server
version: 0.1.0.0
extra-source-files:
- README.md
author: Author name here
github: githubuser/sleepchart-server
license: BSD3
executables:
  sleepchart-server-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - sleepchart-server
    - sleepchart-server
    - sleepchart-server
